close all;
clear;
clc;

%% ========================================================================
% MAKE EXPERIMENT 3 FIGURES - OPTIMIZED
%
% Numerical inputs:
%   results/experiment3_availability/
%       experiment3_haps_summary.csv
%       experiment3_leo_summary.csv
%
% Outputs:
%   results/paper_figures_experiment3/
%       haps_availability.png/.pdf/.fig
%       experiment3_leo_compensation.png/.pdf/.fig
%
% Notes
% -----
% - The visual design of the supplied final plotting script is preserved.
% - Legacy CSV columns named FTS/BTS are read for compatibility only:
%       FTS -> current FA results
%       BTS -> current BE results
% - No simulation is rerun here.
% ========================================================================

%% ========================================================================
% Repository
% ========================================================================

thisFile = mfilename('fullpath');

if isempty(thisFile)
    error('Save this script before running it.');
end

repoRoot = fileparts(thisFile);

while ~isfolder(fullfile(repoRoot,'.git'))

    parentDir = fileparts(repoRoot);

    if strcmp(parentDir,repoRoot)
        error('Could not locate Git repository root from:\n%s',thisFile);
    end

    repoRoot = parentDir;
end

setupFile = fullfile( ...
    repoRoot,'matlab','setup','setup_paths.m');

assert(isfile(setupFile), ...
    'setup_paths.m not found:\n%s',setupFile);

addpath(fullfile(repoRoot,'matlab','setup'),'-begin');
setup_paths;
cd(repoRoot);

inputDir = fullfile( ...
    repoRoot,'results','experiment3_availability');

outDir = fullfile( ...
    repoRoot,'results','paper_figures_experiment3');

hapsFile = fullfile( ...
    inputDir,'experiment3_haps_summary.csv');

leoFile = fullfile( ...
    inputDir,'experiment3_leo_summary.csv');

assert(isfile(hapsFile), ...
    'HAPS summary file not found:\n%s',hapsFile);

assert(isfile(leoFile), ...
    'LEO summary file not found:\n%s',leoFile);

if ~isfolder(outDir)
    mkdir(outDir);
end

%% ========================================================================
% Load and validate data
% ========================================================================

Thaps = readtable( ...
    hapsFile, ...
    'TextType','string');

Tleo = readtable( ...
    leoFile, ...
    'TextType','string');

requiredHAPS = { ...
    'HAPS_Max', ...
    'FTS_K', ...
    'FTS_Bound_m', ...
    'FTS_HAPS', ...
    'FTS_LEO', ...
    'FTS_MEO', ...
    'FTS_GEO', ...
    'BTS_K', ...
    'BTS_Bound_m'};

requiredLEO = { ...
    'LEO_Available', ...
    'CandidateCount_LEO', ...
    'FullPoolBound_m', ...
    'LEO_FTS_K', ...
    'LEO_FTS_Bound_m', ...
    'LEO_FTS_Feasible', ...
    'LEO_FTS_Evaluations', ...
    'LEO_BTS_K', ...
    'LEO_BTS_Bound_m', ...
    'LEO_BTS_Feasible', ...
    'LEO_BTS_Evaluations'};

assertTableVariables( ...
    Thaps,requiredHAPS,'HAPS summary');

assertTableVariables( ...
    Tleo,requiredLEO,'LEO summary');

target_m = 0.6;

%% ========================================================================
% Common style
% ========================================================================

style = struct;

style.fontName   = 'Times New Roman';
style.axisFS     = 11;
style.labelFS    = 14;
style.legendFS   = 8;
style.lineWidth  = 1.8;
style.markerSize = 7;
style.gridAlpha  = 0.22;

% Architecture colors
style.cHAPS = [0.0000 0.4470 0.7410];
style.cLEO  = [0.8500 0.3250 0.0980];
style.cMEO  = [0.9290 0.6940 0.1250];
style.cGEO  = [0.4940 0.1840 0.5560];

% Curve colors
style.cNoSelection = [0.0000 0.4470 0.7410];
style.cFA          = [0.8500 0.3250 0.0980];
style.cBE          = [0.4660 0.6740 0.1880];
style.cTarget      = [0.50 0.50 0.50];

figureSize = [1 1 3.45 3.24];

%% ========================================================================
% FIGURE 1 - HAPS AVAILABILITY
% ========================================================================

[~,ordH] = sort( ...
    double(Thaps.HAPS_Max), ...
    'descend');

T = Thaps(ordH,:);

xH = 1:height(T);

xLabels = ...
    string(T.HAPS_Max);

faK = ...
    double(T.FTS_K);

beK = ...
    double(T.BTS_K);

topKLabels = ...
    makePairLabels(faK,beK);

barData = [ ...
    double(T.FTS_HAPS), ...
    double(T.FTS_LEO), ...
    double(T.FTS_MEO), ...
    double(T.FTS_GEO)];

fig1 = figure( ...
    'Name','Experiment 3 - HAPS availability', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Visible','on', ...
    'Units','inches', ...
    'Position',figureSize);

plotPos = [0.18 0.16 0.72 0.68];

%% Hidden bar axis

axBar = axes( ...
    'Parent',fig1, ...
    'Position',plotPos, ...
    'Color','none');

hold(axBar,'on');

b = bar( ...
    axBar, ...
    xH, ...
    barData, ...
    'stacked', ...
    'BarWidth',0.65, ...
    'LineWidth',0.8);

b(1).FaceColor = style.cHAPS;
b(2).FaceColor = style.cLEO;
b(3).FaceColor = style.cMEO;
b(4).FaceColor = style.cGEO;

xlim(axBar,[0.4 3.6]);

xticks(axBar,xH);
xticklabels(axBar,xLabels);

xlabel( ...
    axBar, ...
    'Available HAPS', ...
    'FontName',style.fontName, ...
    'FontSize',style.labelFS);

ylim(axBar,[0 24]);

yticks(axBar,[]);
axBar.YColor = 'none';

set( ...
    axBar, ...
    'FontName',style.fontName, ...
    'FontSize',style.axisFS, ...
    'LineWidth',1.0, ...
    'TickDir','in', ...
    'Box','off', ...
    'Layer','top');

%% Architecture counts inside stacked bars

addStackedBarLabels( ...
    axBar, ...
    xH, ...
    barData, ...
    style.fontName);

%% Bound axis

axBound = axes( ...
    'Parent',fig1, ...
    'Position',plotPos, ...
    'Color','none', ...
    'XAxisLocation','bottom', ...
    'YAxisLocation','left');

hold(axBound,'on');
grid(axBound,'on');

axBound.XTick = [];
axBound.XColor = 'none';

xlim(axBound,[0.4 3.6]);

faBoundH = ...
    double(T.FTS_Bound_m);

beBoundH = ...
    double(T.BTS_Bound_m);

hFA = plot( ...
    axBound, ...
    xH, ...
    faBoundH, ...
    '-o', ...
    'Color','k', ...
    'LineWidth',style.lineWidth, ...
    'MarkerSize',style.markerSize, ...
    'MarkerFaceColor','k', ...
    'DisplayName','FA');

hBE = plot( ...
    axBound, ...
    xH, ...
    beBoundH, ...
    '--s', ...
    'Color',style.cBE, ...
    'LineWidth',1.6, ...
    'MarkerSize',style.markerSize, ...
    'MarkerFaceColor','w', ...
    'DisplayName','BE');

hTarget = yline( ...
    axBound, ...
    target_m, ...
    '--', ...
    'Color',style.cTarget, ...
    'LineWidth',1.2, ...
    'DisplayName','Target');

% Preserve the final paper scale.
ylim(axBound,[0.56 0.625]);
yticks(axBound,[0.56 0.58 0.60 0.62]);

warnIfClipped( ...
    [faBoundH;beBoundH], ...
    ylim(axBound), ...
    'HAPS availability');

ylabel( ...
    axBound, ...
    'Position bound [m]', ...
    'FontName',style.fontName, ...
    'FontSize',style.labelFS, ...
    'Color','k');

axBound.YColor = 'k';

set( ...
    axBound, ...
    'FontName',style.fontName, ...
    'FontSize',style.axisFS, ...
    'LineWidth',1.0, ...
    'GridAlpha',style.gridAlpha, ...
    'GridLineStyle','-', ...
    'TickDir','in', ...
    'Box','on', ...
    'Layer','top');

%% Architecture legend handles

hHAPS = patch( ...
    axBound,nan,nan,style.cHAPS, ...
    'EdgeColor','k', ...
    'LineWidth',0.8);

hLEO = patch( ...
    axBound,nan,nan,style.cLEO, ...
    'EdgeColor','k', ...
    'LineWidth',0.8);

hMEO = patch( ...
    axBound,nan,nan,style.cMEO, ...
    'EdgeColor','k', ...
    'LineWidth',0.8);

hGEO = patch( ...
    axBound,nan,nan,style.cGEO, ...
    'EdgeColor','k', ...
    'LineWidth',0.8);

lg1 = legend( ...
    axBound, ...
    [hHAPS hLEO hMEO hGEO hFA hBE hTarget], ...
    {'HAPS','LEO','MEO','GEO','FA','BE','Target'}, ...
    'Location','northwest', ...
    'NumColumns',2, ...
    'Box','off', ...
    'FontName',style.fontName, ...
    'FontSize',style.legendFS);

lg1.ItemTokenSize = [10 7];

%% Top x-axis: selected transmitters

axTopH = axes( ...
    'Parent',fig1, ...
    'Position',plotPos, ...
    'Color','none', ...
    'XAxisLocation','top', ...
    'YAxisLocation','right', ...
    'XLim',[0.4 3.6], ...
    'YLim',[0 1], ...
    'XTick',xH, ...
    'XTickLabel',cellstr(topKLabels), ...
    'YTick',[], ...
    'Box','off', ...
    'FontName',style.fontName, ...
    'FontSize',10, ...
    'LineWidth',1.0, ...
    'TickDir','in');

axTopH.YColor = 'none';
axTopH.XColor = 'k';

if all(faK==beK)
    topTitleH = 'Transmitters used';
else
    topTitleH = 'Transmitters used [FA / BE]';
end

hTopH = xlabel( ...
    axTopH, ...
    topTitleH, ...
    'FontName',style.fontName, ...
    'FontSize',10, ...
    'Color','k');

hTopH.Units = 'normalized';
hTopH.Position = [0.5 1.13 0];

linkaxes( ...
    [axBar axBound axTopH], ...
    'x');

%% Export Figure 1

baseH = fullfile( ...
    outDir,'haps_availability');

saveFigureAll( ...
    fig1, ...
    baseH);

%% ========================================================================
% FIGURE 2 - LEO COMPENSATION WITHOUT HAPS
% ========================================================================

[~,idxL] = sort( ...
    double(Tleo.LEO_Available), ...
    'ascend');

T = Tleo(idxL,:);

xAvail = ...
    double(T.LEO_Available);

xTotal = ...
    double(T.CandidateCount_LEO);

fullBound = ...
    double(T.FullPoolBound_m);

faBound = ...
    double(T.LEO_FTS_Bound_m);

beBound = ...
    double(T.LEO_BTS_Bound_m);

faEval = ...
    double(T.LEO_FTS_Evaluations);

beEval = ...
    double(T.LEO_BTS_Evaluations);

faFeasible = ...
    logical(T.LEO_FTS_Feasible);

beFeasible = ...
    logical(T.LEO_BTS_Feasible);

fig2 = figure( ...
    'Name','Experiment 3 - LEO compensation', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Visible','on', ...
    'Units','inches', ...
    'Position',figureSize);

ax2 = axes( ...
    'Parent',fig2);

ax2.Position = [0.18 0.17 0.74 0.61];

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

pNo = plot( ...
    ax2, ...
    xAvail, ...
    fullBound, ...
    '-o', ...
    'Color',style.cNoSelection, ...
    'LineWidth',1.8, ...
    'MarkerSize',7, ...
    'MarkerFaceColor','none', ...
    'DisplayName','No Selection');

pFA = plot( ...
    ax2, ...
    xAvail, ...
    faBound, ...
    '--s', ...
    'Color',style.cFA, ...
    'LineWidth',1.7, ...
    'MarkerSize',7, ...
    'MarkerFaceColor','none', ...
    'DisplayName','FA');

pBE = plot( ...
    ax2, ...
    xAvail, ...
    beBound, ...
    ':^', ...
    'Color',style.cBE, ...
    'LineWidth',2.0, ...
    'MarkerSize',8, ...
    'MarkerFaceColor','none', ...
    'DisplayName','BE');

pTarget = yline( ...
    ax2, ...
    target_m, ...
    '--', ...
    'Color',style.cTarget, ...
    'LineWidth',1.2, ...
    'DisplayName','Target');

%% Bottom x-axis

xlim(ax2,[7 21]);

xticks(ax2,xAvail);
xticklabels(ax2,string(xAvail));

xlabel( ...
    ax2, ...
    'Available LEO', ...
    'FontName',style.fontName, ...
    'FontSize',13);

%% Y-axis

% Preserve the final paper scale.
ylim(ax2,[0.56 0.625]);
yticks(ax2,[0.56 0.58 0.60 0.62]);

warnIfClipped( ...
    [fullBound;faBound;beBound], ...
    ylim(ax2), ...
    'LEO compensation');

ylabel( ...
    ax2, ...
    'Position bound [m]', ...
    'FontName',style.fontName, ...
    'FontSize',13);

set( ...
    ax2, ...
    'FontName',style.fontName, ...
    'FontSize',11, ...
    'LineWidth',1.0, ...
    'GridAlpha',style.gridAlpha, ...
    'TickDir','in', ...
    'Layer','top');

%% Evaluation labels near selected-bound markers

evaluationSummary = ...
    strings(height(T),1);

for k = 1:height(T)

    pairText = sprintf( ...
        '%s / %s', ...
        compactEval(faEval(k)), ...
        compactEval(beEval(k)));

    evaluationSummary(k) = pairText;

    if ~faFeasible(k) && ~beFeasible(k)
        continue;
    end

    yCandidates = [faBound(k),beBound(k)];
    yCandidates = yCandidates(isfinite(yCandidates));

    if isempty(yCandidates)
        continue;
    end

    yBase = min(yCandidates);

    xShift = 0;

    if k==height(T)
        xShift = -0.30;
    end

    if faFeasible(k)

        text( ...
            ax2, ...
            xAvail(k)+xShift, ...
            yBase-0.0030, ...
            sprintf('FA: %s',compactEval(faEval(k))), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','top', ...
            'FontName',style.fontName, ...
            'FontSize',7, ...
            'Color',style.cFA, ...
            'BackgroundColor','w', ...
            'Margin',0.2);
    end

    if beFeasible(k)

        text( ...
            ax2, ...
            xAvail(k)+xShift, ...
            yBase-0.0062, ...
            sprintf('BE: %s',compactEval(beEval(k))), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','top', ...
            'FontName',style.fontName, ...
            'FontSize',7.5, ...
            'Color',style.cBE, ...
            'BackgroundColor','w', ...
            'Margin',0.2);
    end
end

%% Legend

lg2 = legend( ...
    ax2, ...
    [pNo pFA pBE pTarget], ...
    {'No Selection','FA','BE','Target'}, ...
    'Location','northeast', ...
    'Box','off', ...
    'FontName',style.fontName, ...
    'FontSize',8);

lg2.ItemTokenSize = [12 7];

%% Top x-axis: total candidate pool

axTop = axes( ...
    'Parent',fig2, ...
    'Position',ax2.Position, ...
    'Color','none', ...
    'XAxisLocation','top', ...
    'YAxisLocation','right', ...
    'XLim',ax2.XLim, ...
    'YLim',ax2.YLim, ...
    'XTick',xAvail, ...
    'XTickLabel',string(xTotal), ...
    'YTick',[], ...
    'Box','off', ...
    'FontName',style.fontName, ...
    'FontSize',10, ...
    'LineWidth',1.0, ...
    'TickDir','in');

axTop.YColor = 'none';
axTop.XColor = 'k';

hTopLabel = xlabel( ...
    axTop, ...
    'Total candidate pool', ...
    'FontName',style.fontName, ...
    'FontSize',10, ...
    'Color','k');

hTopLabel.Units = 'normalized';
hTopLabel.Position = [0.5 1.14 0];

linkaxes( ...
    [ax2 axTop], ...
    'x');

%% Export Figure 2

baseL = fullfile( ...
    outDir,'experiment3_leo_compensation');

saveFigureAll( ...
    fig2, ...
    baseL);

%% ========================================================================
% Report
% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('EXPERIMENT 3 PAPER FIGURES GENERATED\n');
fprintf('============================================================\n');

fprintf('HAPS figure:\n');
fprintf('  %s.pdf\n',baseH);

fprintf('LEO figure:\n');
fprintf('  %s.pdf\n',baseL);

fprintf('\nLEO mean subset evaluations [FA / BE]:\n');

for k = 1:height(T)

    if ~faFeasible(k) && ~beFeasible(k)

        statusText = 'infeasible';

    else

        statusText = char(evaluationSummary(k));
    end

    fprintf( ...
        '  LEO=%d -> %s\n', ...
        xAvail(k), ...
        statusText);
end

fprintf('============================================================\n');

close(fig1);
close(fig2);

%% ========================================================================
% Local functions
% ========================================================================

function assertTableVariables(T,requiredVars,tableName)

    vars = ...
        string(T.Properties.VariableNames);

    missing = ...
        string(requiredVars( ...
        ~ismember(requiredVars,vars)));

    if ~isempty(missing)

        error( ...
            '%s is missing required variables: %s', ...
            tableName, ...
            strjoin(missing,', '));
    end
end

function labels = makePairLabels(a,b)

    a = a(:);
    b = b(:);

    labels = strings(numel(a),1);

    for k = 1:numel(a)

        if a(k)==b(k)

            labels(k) = sprintf('%d',a(k));

        else

            labels(k) = sprintf('%d/%d',a(k),b(k));
        end
    end
end

function addStackedBarLabels(ax,x,barData,fontName)

    cumBase = ...
        zeros(1,size(barData,1));

    txtColors = { ...
        [1 1 1], ...
        [1 1 1], ...
        [0 0 0], ...
        [1 1 1]};

    smallThreshold = 1;
    xOffsetSide = 0.13;

    for j = 1:size(barData,2)

        yj = ...
            barData(:,j).';

        yCenter = ...
            cumBase+yj/2;

        for k = 1:numel(x)

            if yj(k)<=0
                continue;
            end

            if yj(k)<=smallThreshold

                text( ...
                    ax, ...
                    x(k)+xOffsetSide, ...
                    yCenter(k), ...
                    sprintf('%d',yj(k)), ...
                    'HorizontalAlignment','left', ...
                    'VerticalAlignment','middle', ...
                    'FontName',fontName, ...
                    'FontSize',9, ...
                    'FontWeight','bold', ...
                    'Color','k', ...
                    'BackgroundColor','w', ...
                    'Margin',0.3);

            else

                text( ...
                    ax, ...
                    x(k), ...
                    yCenter(k), ...
                    sprintf('%d',yj(k)), ...
                    'HorizontalAlignment','center', ...
                    'VerticalAlignment','middle', ...
                    'FontName',fontName, ...
                    'FontSize',9, ...
                    'FontWeight','bold', ...
                    'Color',txtColors{j});
            end
        end

        cumBase = ...
            cumBase+yj;
    end
end

function txt = compactEval(v)

    if ~isfinite(v)

        txt = 'n/a';

    elseif v>=10000

        txt = sprintf('%.1fk',v/1000);

    elseif v>=1000

        txt = sprintf('%.2fk',v/1000);

    else

        txt = sprintf('%.0f',v);
    end
end

function warnIfClipped(values,yLim,figureName)

    values = ...
        values(isfinite(values));

    if isempty(values)
        return;
    end

    if any(values<yLim(1)) || ...
       any(values>yLim(2))

        warning( ...
            ['%s contains values outside the preserved paper ' ...
             'y-axis range [%.3f, %.3f] m. The plot scale was ' ...
             'not changed automatically.'], ...
            figureName, ...
            yLim(1), ...
            yLim(2));
    end
end

function saveFigureAll(fig,baseFile)

    drawnow;

    exportgraphics( ...
        fig, ...
        [baseFile '.png'], ...
        'Resolution',400);

    exportgraphics( ...
        fig, ...
        [baseFile '.pdf'], ...
        'ContentType','vector');

    savefig( ...
        fig, ...
        [baseFile '.fig']);
end
