close all;
clear;
clc;

%% ========================================================================
% MAKE EXPERIMENT 1 FIGURES
%
% Combines the previous temporal-plot script and standalone legend script.
%
% Numerical inputs:
%   results/experiment1_temporal/
%       experiment1_geometry.mat
%       experiment1_results.mat
%
% Outputs: SIX SEPARATE FIGURES
%   results/experiment1_temporal/figures/
%       temporal_fa_be_4epochs_60s.pdf/png/fig
%       skyplot_t000s.pdf/png/fig
%       skyplot_t060s.pdf/png/fig
%       skyplot_t120s.pdf/png/fig
%       skyplot_t180s.pdf/png/fig
%       skyplot_legend.pdf/png/fig
%
% IMPORTANT:
%   - This script DOES NOT rerun geometry, propagation, link budget,
%     FA, or BE.
%   - It only reads the saved Experiment 1 MAT files.
%   - Plot styling follows the two supplied plotting scripts.
% ========================================================================

%% ========================================================================
% Locate repository root
% ========================================================================

thisFile = mfilename('fullpath');

if isempty(thisFile)
    error('Save this script before running it.');
end

repoRoot = fileparts(thisFile);

while ~isfolder(fullfile(repoRoot,'.git'))

    parentDir = fileparts(repoRoot);

    if strcmp(parentDir,repoRoot)
        error('Could not locate Git repository root from:\n%s',thisFile);
    end

    repoRoot = parentDir;
end

setupFile = fullfile( ...
    repoRoot,'matlab','setup','setup_paths.m');

assert(isfile(setupFile), ...
    'setup_paths.m not found:\n%s',setupFile);

addpath(fullfile(repoRoot,'matlab','setup'),'-begin');
setup_paths;
cd(repoRoot);

%% ========================================================================
% Inputs and outputs
% ========================================================================

experimentDir = fullfile( ...
    repoRoot,'results','experiment1_temporal');

geometryMat = fullfile( ...
    experimentDir,'experiment1_geometry.mat');

resultsMat = fullfile( ...
    experimentDir,'experiment1_results.mat');

outDir = fullfile( ...
    experimentDir,'figures');

if ~isfile(geometryMat)
    error('Geometry MAT not found: %s',geometryMat);
end

if ~isfile(resultsMat)
    error('Results MAT not found: %s',resultsMat);
end

if ~isfolder(outDir)
    mkdir(outDir);
end

fprintf('\n');
fprintf('============================================================\n');
fprintf('EXPERIMENT 1 - PAPER FIGURES\n');
fprintf('============================================================\n');
fprintf('Repository : %s\n',repoRoot);
fprintf('Geometry   : %s\n',geometryMat);
fprintf('Results    : %s\n',resultsMat);
fprintf('Output dir : %s\n',outDir);
fprintf('============================================================\n');

%% ========================================================================
% Load saved numerical results
% ========================================================================

G = load(geometryMat);
R = load(resultsMat);

requiredGeometry = { ...
    'epochs', ...
    'timeOffset_s'};

for k = 1:numel(requiredGeometry)

    if ~isfield(G,requiredGeometry{k})
        error( ...
            'Geometry MAT missing variable: %s', ...
            requiredGeometry{k});
    end
end

requiredResults = { ...
    'Tsummary', ...
    'timeOffset_s', ...
    'Label', ...
    'Architecture'};

for k = 1:numel(requiredResults)

    if ~isfield(R,requiredResults{k})
        error( ...
            'Results MAT missing variable: %s', ...
            requiredResults{k});
    end
end

epochs = G.epochs;
Tsummary = R.Tsummary;

timeOffset_s = double(R.timeOffset_s(:));
Label = string(R.Label(:)); %#ok<NASGU>
Architecture = upper(string(R.Architecture(:)));

%% Current selection variable names

if isfield(R,'SelectedFA')
    SelectedFA = logical(R.SelectedFA);
elseif isfield(R,'SelectedFTS')
    SelectedFA = logical(R.SelectedFTS);
else
    error('Results MAT does not contain SelectedFA.');
end

if isfield(R,'SelectedBE')
    SelectedBE = logical(R.SelectedBE);
elseif isfield(R,'SelectedBTS')
    SelectedBE = logical(R.SelectedBTS);
else
    error('Results MAT does not contain SelectedBE.');
end

expectedTimes = [0;60;120;180];

if ~isequal(timeOffset_s,expectedTimes)
    error('Expected epochs t = [0 60 120 180] s.');
end

if numel(epochs) ~= numel(timeOffset_s)
    error('Geometry/results epoch counts do not match.');
end

if size(SelectedFA,2) ~= numel(timeOffset_s) || ...
   size(SelectedBE,2) ~= numel(timeOffset_s)

    error('Selected-set matrices do not match temporal grid.');
end

%% ========================================================================
% Extract current FA/BE summary columns
% ========================================================================

requiredCurrentVars = { ...
    'NoSelection_AlphaCRB_m', ...
    'FA_AlphaCRB_m', ...
    'BE_AlphaCRB_m', ...
    'FA_K', ...
    'BE_K', ...
    'FA_Evaluations', ...
    'BE_Evaluations'};

for k = 1:numel(requiredCurrentVars)

    if ~ismember( ...
            requiredCurrentVars{k}, ...
            Tsummary.Properties.VariableNames)

        error( ...
            'Tsummary missing variable: %s', ...
            requiredCurrentVars{k});
    end
end

time_min = timeOffset_s/60;

boundNoSelection_m = ...
    double(Tsummary.NoSelection_AlphaCRB_m(:));

boundFA_m = ...
    double(Tsummary.FA_AlphaCRB_m(:));

boundBE_m = ...
    double(Tsummary.BE_AlphaCRB_m(:));

Kfa = double(Tsummary.FA_K(:));
Kbe = double(Tsummary.BE_K(:));

Efa = double(Tsummary.FA_Evaluations(:));
Ebe = double(Tsummary.BE_Evaluations(:));

%% ========================================================================
% Common paper style
% ========================================================================

style.fontName       = 'Times New Roman';
style.axisFontSize   = 11;
style.labelFontSize  = 14;
style.legendFontSize = 10;
style.lineWidth      = 1.8;
style.markerSize     = 7;
style.gridAlpha      = 0.20;

target_m = 0.6;

style.cNoSelection = [0.850 0.325 0.098];
style.cFA          = [0.000 0.447 0.741];
style.cBE          = [0.466 0.674 0.188];
style.cTarget      = [0.20 0.20 0.20];

archList = ["HAPS","LEO","MEO","GEO"];

archColors = [ ...
    0.0000 0.4470 0.7410
    0.8500 0.3250 0.0980
    0.9290 0.6940 0.1250
    0.4940 0.1840 0.5560];

%% ========================================================================
% FIGURE 1 - Temporal position bound
% ========================================================================

fig = figure( ...
    'Name','Temporal FA-BE', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 3.45 3.24]);

ax = axes('Parent',fig);

ax.Units = 'normalized';
ax.Position = [0.17 0.15 0.75 0.67];

hold(ax,'on');
grid(ax,'on');
box(ax,'on');

pNo = plot( ...
    ax,time_min,boundNoSelection_m, ...
    '-s', ...
    'Color',style.cNoSelection, ...
    'LineWidth',style.lineWidth, ...
    'MarkerSize',style.markerSize, ...
    'MarkerFaceColor','none', ...
    'DisplayName','No Selection');

pFA = plot( ...
    ax,time_min,boundFA_m, ...
    '-^', ...
    'Color',style.cFA, ...
    'LineWidth',style.lineWidth, ...
    'MarkerSize',style.markerSize, ...
    'MarkerFaceColor','none', ...
    'DisplayName','FA');

pBE = plot( ...
    ax,time_min,boundBE_m, ...
    '-o', ...
    'Color',style.cBE, ...
    'LineWidth',style.lineWidth, ...
    'MarkerSize',style.markerSize, ...
    'MarkerFaceColor','none', ...
    'DisplayName','BE');

yline( ...
    ax,target_m,'--', ...
    'Color',style.cTarget, ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xlabel( ...
    ax,'Time [min]', ...
    'FontName',style.fontName, ...
    'FontSize',style.labelFontSize);

ylabel( ...
    ax,'Position bound [m]', ...
    'FontName',style.fontName, ...
    'FontSize',style.labelFontSize);

xticks(ax,[0 1 2 3]);
xlim(ax,[-0.08 3.10]);

allBounds = [ ...
    boundNoSelection_m; ...
    boundFA_m; ...
    boundBE_m; ...
    target_m];

ymin = floor((min(allBounds)-0.010)*1000)/1000;
ymax = ceil((max(allBounds)+0.015)*1000)/1000;

ylim(ax,[ymin ymax]);

text( ...
    ax,2.35,target_m+0.006,'Target', ...
    'FontName',style.fontName, ...
    'FontSize',style.axisFontSize, ...
    'Color',style.cTarget);

set( ...
    ax, ...
    'FontName',style.fontName, ...
    'FontSize',style.axisFontSize, ...
    'LineWidth',1.0, ...
    'GridAlpha',style.gridAlpha, ...
    'Layer','top');

%% K labels

xOffset = [0.10 0 0 -0.20];

for k = 1:numel(time_min)

    if Kfa(k) == Kbe(k)
        kText = sprintf('K=%d',Kfa(k));
    else
        kText = sprintf('K=%d/%d',Kfa(k),Kbe(k));
    end

    yLabel = ...
        min(boundFA_m(k),boundBE_m(k)) - 0.0032;

    text( ...
        ax, ...
        time_min(k)+xOffset(k), ...
        yLabel, ...
        kText, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','top', ...
        'FontName',style.fontName, ...
        'FontSize',8, ...
        'Color','k', ...
        'BackgroundColor','w', ...
        'Margin',0.3);
end

%% Top x-axis with FA/BE evaluation counts

evalLabels = strings(size(time_min));

for k = 1:numel(time_min)

    evalLabels(k) = ...
        sprintf( ...
        '%s/%s', ...
        shortEval(Efa(k)), ...
        shortEval(Ebe(k)));
end

axTop = axes( ...
    'Position',ax.Position, ...
    'Color','none', ...
    'XAxisLocation','top', ...
    'YAxisLocation','right', ...
    'XLim',ax.XLim, ...
    'YLim',ax.YLim, ...
    'XTick',time_min, ...
    'XTickLabel',cellstr(evalLabels), ...
    'YTick',[], ...
    'Box','off', ...
    'FontName',style.fontName, ...
    'FontSize',8, ...
    'LineWidth',1.0, ...
    'XColor','k', ...
    'YColor','none');

try
    axTop.XRuler.TickLabelGapOffset = 2;
catch
end

axTop.TickDir = 'in';

linkaxes([ax axTop],'x');

text( ...
    axTop,0.5,1.15,'Evaluations [FA/BE]', ...
    'Units','normalized', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',style.fontName, ...
    'FontSize',8.5, ...
    'Color','k');

%% Temporal legend

lg = legend( ...
    ax,[pNo pFA pBE], ...
    {'No Selection','FA','BE'}, ...
    'Location','none', ...
    'Box','off', ...
    'FontName',style.fontName, ...
    'FontSize',style.legendFontSize);

lg.ItemTokenSize = [18 10];
lg.Units = 'normalized';
lg.Position = [0.22 0.37 0.30 0.15];

%% Save temporal figure

temporalBase = ...
    fullfile(outDir,'temporal_fa_be_4epochs_60s');

saveFigureAll(fig,temporalBase);

close(fig);

%% ========================================================================
% FIGURES 2-5 - Four separate skyplots
% ========================================================================

for k = 1:numel(timeOffset_s)

    tsec = timeOffset_s(k);

    figSky = figure( ...
        'Name',sprintf('Skyplot t=%d s',tsec), ...
        'NumberTitle','off', ...
        'Color','w', ...
        'Units','inches', ...
        'Position',[1 1 3.45 3.25]);

    pax = polaraxes('Parent',figSky);

    makeSkyplot( ...
        pax, ...
        epochs(k).Azimuth_deg(:), ...
        epochs(k).Elevation_deg(:), ...
        Architecture, ...
        logical(epochs(k).Visible(:)), ...
        SelectedFA(:,k), ...
        SelectedBE(:,k), ...
        archList, ...
        archColors, ...
        style);

    baseName = ...
        sprintf('skyplot_t%03ds',tsec);

    saveFigureAll( ...
        figSky, ...
        fullfile(outDir,baseName));

    close(figSky);
end

%% ========================================================================
% FIGURE 6 - Standalone skyplot legend
% ========================================================================

figLegend = figure( ...
    'Name','Skyplot legend', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 6.9 0.55], ...
    'MenuBar','none', ...
    'ToolBar','none');

axLegend = axes( ...
    'Parent',figLegend, ...
    'Position',[0 0 1 1], ...
    'XLim',[0 1], ...
    'YLim',[0 1], ...
    'Visible','off');

hold(axLegend,'on');

fontName = 'Times New Roman';
fontSize = 10;
markerSize = 7.5;
y = 0.50;

% Same spacing as supplied standalone legend.
x = [ ...
    0.025 ...
    0.145 ...
    0.260 ...
    0.375 ...
    0.505 ...
    0.615 ...
    0.750 ...
    0.865];

%% Architecture entries

plot( ...
    axLegend,x(1),y,'o', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor',archColors(1,:), ...
    'MarkerEdgeColor',archColors(1,:));

text( ...
    axLegend,x(1)+0.018,y,'HAPS', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

plot( ...
    axLegend,x(2),y,'o', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor',archColors(2,:), ...
    'MarkerEdgeColor',archColors(2,:));

text( ...
    axLegend,x(2)+0.018,y,'LEO', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

plot( ...
    axLegend,x(3),y,'o', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor',archColors(3,:), ...
    'MarkerEdgeColor',archColors(3,:));

text( ...
    axLegend,x(3)+0.018,y,'MEO', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

plot( ...
    axLegend,x(4),y,'o', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor',archColors(4,:), ...
    'MarkerEdgeColor',archColors(4,:));

text( ...
    axLegend,x(4)+0.018,y,'GEO', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

%% Selection-status entries

% Both selected by FA and BE
plot( ...
    axLegend,x(5),y,'o', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor','k', ...
    'MarkerEdgeColor','k');

text( ...
    axLegend,x(5)+0.018,y,'Both', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

% FA only
plot( ...
    axLegend,x(6),y,'^', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize+0.5, ...
    'MarkerFaceColor','k', ...
    'MarkerEdgeColor','k');

text( ...
    axLegend,x(6)+0.018,y,'FA only', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

% BE only
plot( ...
    axLegend,x(7),y,'s', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor','k', ...
    'MarkerEdgeColor','k');

text( ...
    axLegend,x(7)+0.018,y,'BE only', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

% Unselected
plot( ...
    axLegend,x(8),y,'o', ...
    'LineStyle','none', ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor','k', ...
    'LineWidth',1.0);

text( ...
    axLegend,x(8)+0.018,y,'Unselected', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'VerticalAlignment','middle');

legendBase = ...
    fullfile(outDir,'skyplot_legend');

drawnow;

exportgraphics( ...
    figLegend,[legendBase '.pdf'], ...
    'ContentType','vector', ...
    'BackgroundColor','white');

exportgraphics( ...
    figLegend,[legendBase '.png'], ...
    'Resolution',400, ...
    'BackgroundColor','white');

savefig( ...
    figLegend,[legendBase '.fig']);

close(figLegend);

%% ========================================================================
% Final report
% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('SIX FIGURES GENERATED SUCCESSFULLY\n');
fprintf('============================================================\n');

fprintf('Output folder:\n  %s\n\n',outDir);

fprintf('1) temporal_fa_be_4epochs_60s.pdf/png/fig\n');
fprintf('2) skyplot_t000s.pdf/png/fig\n');
fprintf('3) skyplot_t060s.pdf/png/fig\n');
fprintf('4) skyplot_t120s.pdf/png/fig\n');
fprintf('5) skyplot_t180s.pdf/png/fig\n');
fprintf('6) skyplot_legend.pdf/png/fig\n');

fprintf('\nFA/BE evaluations shown on temporal plot:\n');

for k = 1:numel(timeOffset_s)

    fprintf( ...
        '  t=%3d s -> %s/%s | K=%d/%d\n', ...
        timeOffset_s(k), ...
        shortEval(Efa(k)), ...
        shortEval(Ebe(k)), ...
        Kfa(k), ...
        Kbe(k));
end

fprintf('============================================================\n');

%% ========================================================================
% Local functions
% ========================================================================

function s = shortEval(v)

    if v >= 1000
        s = sprintf('%.2fk',v/1000);
    else
        s = sprintf('%d',round(v));
    end
end

function makeSkyplot( ...
    pax, ...
    azimuth_deg, ...
    elevation_deg, ...
    architecture, ...
    visible, ...
    selectedFA, ...
    selectedBE, ...
    archList, ...
    archColors, ...
    style)

    hold(pax,'on');

    architecture = string(architecture(:));
    visible = logical(visible(:));
    selectedFA = logical(selectedFA(:));
    selectedBE = logical(selectedBE(:));

    theta = ...
        deg2rad(mod(azimuth_deg,360));

    rho = ...
        90-elevation_deg;

    selectedBoth = ...
        visible & selectedFA & selectedBE;

    selectedFAOnly = ...
        visible & selectedFA & ~selectedBE;

    selectedBEOnly = ...
        visible & ~selectedFA & selectedBE;

    selectedNeither = ...
        visible & ~selectedFA & ~selectedBE;

    for aa = 1:numel(archList)

        idxArch = ...
            architecture == archList(aa);

        %% Unselected: open circle

        idx = ...
            idxArch & selectedNeither;

        if any(idx)

            polarscatter( ...
                pax, ...
                theta(idx), ...
                rho(idx), ...
                32, ...
                archColors(aa,:), ...
                'o', ...
                'LineWidth',1.0, ...
                'HandleVisibility','off');
        end

        %% Selected by both: filled circle

        idx = ...
            idxArch & selectedBoth;

        if any(idx)

            polarscatter( ...
                pax, ...
                theta(idx), ...
                rho(idx), ...
                44, ...
                archColors(aa,:), ...
                'o', ...
                'filled', ...
                'MarkerEdgeColor','k', ...
                'LineWidth',0.7, ...
                'HandleVisibility','off');
        end

        %% FA only: filled triangle

        idx = ...
            idxArch & selectedFAOnly;

        if any(idx)

            polarscatter( ...
                pax, ...
                theta(idx), ...
                rho(idx), ...
                50, ...
                archColors(aa,:), ...
                '^', ...
                'filled', ...
                'MarkerEdgeColor','k', ...
                'LineWidth',0.7, ...
                'HandleVisibility','off');
        end

        %% BE only: filled square

        idx = ...
            idxArch & selectedBEOnly;

        if any(idx)

            polarscatter( ...
                pax, ...
                theta(idx), ...
                rho(idx), ...
                50, ...
                archColors(aa,:), ...
                's', ...
                'filled', ...
                'MarkerEdgeColor','k', ...
                'LineWidth',0.7, ...
                'HandleVisibility','off');
        end
    end

    set( ...
        pax, ...
        'ThetaZeroLocation','top', ...
        'ThetaDir','clockwise', ...
        'ThetaTick',[0 90 180 270], ...
        'ThetaTickLabel',{'N','E','S','W'}, ...
        'RLim',[0 90], ...
        'RTick',[30 60 90], ...
        'RTickLabel',{'60^\circ','30^\circ','0^\circ'}, ...
        'RAxisLocation',240, ...
        'FontName',style.fontName, ...
        'FontSize',style.axisFontSize, ...
        'GridAlpha',style.gridAlpha, ...
        'LineWidth',0.9);
end

function saveFigureAll(fig,baseFile)

    drawnow;

    exportgraphics( ...
        fig,[baseFile '.pdf'], ...
        'ContentType','vector');

    exportgraphics( ...
        fig,[baseFile '.png'], ...
        'Resolution',400);

    savefig( ...
        fig,[baseFile '.fig']);
end
