clear;
clc;

%% ============================================================
% BUILD 26-TRANSMITTER CANDIDATE POOL
%
% Nominal pool used in the manuscript:
%   4 HAPS
%   8 LEO
%   7 MEO
%   7 GEO
%
% Orbital transmitter states are read from:
%   results/orbital_catalog.mat
%
% The four deterministic HAPS positions are defined directly in
% this script so that the candidate-pool construction has no
% dependency on files outside this repository.
% =============================================================

rootDir = fileparts(mfilename('fullpath'));

if isempty(rootDir)
    rootDir = pwd;
end

cd(rootDir);
setup_paths;

fprintf('\n============================================================\n');
fprintf('BUILD 26-TX CANDIDATE POOL\n');
fprintf('============================================================\n');

%% ============================================================
% Load orbital catalog
% =============================================================

catalogFile = fullfile(rootDir,'results','orbital_catalog.mat');

assert(isfile(catalogFile), ...
    ['Orbital catalog not found:\n%s\n\n' ...
     'Run build_orbital_catalog.m first.'], ...
    catalogFile);

S = load(catalogFile);

requiredVars = { ...
    'TOrbitalCatalog', ...
    'analysisTimeUTC', ...
    'UserPositionECEF', ...
    'userLat_deg', ...
    'userLon_deg', ...
    'userH_m'};

for k = 1:numel(requiredVars)
    assert(isfield(S,requiredVars{k}), ...
        'Variable %s is missing from orbital_catalog.mat.', ...
        requiredVars{k});
end

Tcatalog = S.TOrbitalCatalog;

analysisTimeUTC = S.analysisTimeUTC;
UserPositionECEF = S.UserPositionECEF(:);

userLat_deg = S.userLat_deg;
userLon_deg = S.userLon_deg;
userH_m     = S.userH_m;

requiredColumns = { ...
    'Architecture', ...
    'NORAD_CAT_ID', ...
    'ObjectName', ...
    'X_ECEF_m', ...
    'Y_ECEF_m', ...
    'Z_ECEF_m'};

for k = 1:numel(requiredColumns)
    assert(ismember(requiredColumns{k},Tcatalog.Properties.VariableNames), ...
        'Column %s is missing from TOrbitalCatalog.', ...
        requiredColumns{k});
end

Tcatalog.Architecture = string(Tcatalog.Architecture);
Tcatalog.NORAD_CAT_ID = string(Tcatalog.NORAD_CAT_ID);
Tcatalog.ObjectName   = string(Tcatalog.ObjectName);

%% ============================================================
% Nominal orbital identities and ordering
%
% Ordering follows the manuscript candidate pool:
%   HAPS1-HAPS4
%   LEO1-LEO8
%   MEO1-MEO7
%   GEO1-GEO7
% =============================================================

nominalLEO = [ ...
    "65175"
    "66864"
    "65348"
    "59340"
    "67736"
    "59960"
    "65279"
    "48482"];

nominalMEO = [ ...
    "62362"
    "40081"
    "44115"
    "43231"
    "43234"
    "40080"
    "40079"];

nominalGEO = [ ...
    "41589"
    "41904"
    "42692"
    "43562"
    "43175"
    "43228"
    "38087"];

%% ============================================================
% Deterministic HAPS geometry
%
% Design:
%   altitude  = 20 km
%   azimuths  = [45, 135, 225, 315] deg
%   elevations= [80, 30, 30, 25] deg
%
% The ECEF coordinates below are the deterministic positions used
% by the experiment.
% =============================================================

hapsPositionECEF_m = [ ...
    4300163.5114, -4038986.2343, -2467878.3986;
    4307453.7286, -4015855.7636, -2492621.1302;
    4274112.7443, -4051322.6714, -2492621.1302;
    4285517.3843, -4070008.4688, -2442427.3239];

hapsDesignAzimuth_deg   = [45; 135; 225; 315];
hapsDesignElevation_deg = [80; 30; 30; 25];
hapsAltitude_m          = 20000;

%% ============================================================
% Allocate nominal 26-transmitter pool
% =============================================================

nHAPS = 4;
nLEO  = numel(nominalLEO);
nMEO  = numel(nominalMEO);
nGEO  = numel(nominalGEO);

Npool = nHAPS + nLEO + nMEO + nGEO;

assert(Npool == 26);

PoolIndex    = (1:Npool).';
Label        = strings(Npool,1);
Architecture = strings(Npool,1);
NORAD        = strings(Npool,1);
ObjectName   = strings(Npool,1);
Mask_deg     = zeros(Npool,1);

PositionECEF = zeros(Npool,3);

%% ============================================================
% HAPS entries
% =============================================================

idxHAPS = 1:nHAPS;

Label(idxHAPS)        = compose("HAPS%d",(1:nHAPS).');
Architecture(idxHAPS) = "HAPS";
NORAD(idxHAPS)        = "";
ObjectName(idxHAPS)   = Label(idxHAPS);
Mask_deg(idxHAPS)     = 15;

PositionECEF(idxHAPS,:) = hapsPositionECEF_m;

%% ============================================================
% Orbital entries
% =============================================================

nextIndex = nHAPS + 1;

[nextIndex,Label,Architecture,NORAD,ObjectName,Mask_deg,PositionECEF] = ...
    appendArchitecture( ...
        Tcatalog, ...
        nextIndex, ...
        "LEO", ...
        nominalLEO, ...
        5, ...
        Label, ...
        Architecture, ...
        NORAD, ...
        ObjectName, ...
        Mask_deg, ...
        PositionECEF);

[nextIndex,Label,Architecture,NORAD,ObjectName,Mask_deg,PositionECEF] = ...
    appendArchitecture( ...
        Tcatalog, ...
        nextIndex, ...
        "MEO", ...
        nominalMEO, ...
        5, ...
        Label, ...
        Architecture, ...
        NORAD, ...
        ObjectName, ...
        Mask_deg, ...
        PositionECEF);

[nextIndex,Label,Architecture,NORAD,ObjectName,Mask_deg,PositionECEF] = ...
    appendArchitecture( ...
        Tcatalog, ...
        nextIndex, ...
        "GEO", ...
        nominalGEO, ...
        5, ...
        Label, ...
        Architecture, ...
        NORAD, ...
        ObjectName, ...
        Mask_deg, ...
        PositionECEF);

assert(nextIndex == Npool + 1);

%% ============================================================
% Geometry
% =============================================================

uLOS          = zeros(Npool,3);
Azimuth_deg   = zeros(Npool,1);
Elevation_deg = zeros(Npool,1);
SlantRange_m  = zeros(Npool,1);
Visible       = false(Npool,1);

for k = 1:Npool

    rTx = PositionECEF(k,:).';

    [az,el,range_m,u] = lookAnglesECEF( ...
        rTx, ...
        UserPositionECEF, ...
        userLat_deg, ...
        userLon_deg);

    Azimuth_deg(k)   = az;
    Elevation_deg(k) = el;
    SlantRange_m(k)  = range_m;

    uLOS(k,:) = u.';

    Visible(k) = el >= Mask_deg(k);

end

%% ============================================================
% Sanity checks
% =============================================================

assert(sum(Architecture=="HAPS") == 4);
assert(sum(Architecture=="LEO")  == 8);
assert(sum(Architecture=="MEO")  == 7);
assert(sum(Architecture=="GEO")  == 7);

assert(all(Visible), ...
    'At least one transmitter in the nominal pool is below its elevation mask.');

% The deterministic HAPS ECEF coordinates should reproduce the
% nominal elevation design to numerical precision.
hapsElevationError_deg = ...
    Elevation_deg(idxHAPS) - hapsDesignElevation_deg;

assert(max(abs(hapsElevationError_deg)) < 1e-3, ...
    'HAPS geometry does not reproduce the nominal elevation design.');

%% ============================================================
% Build output table
% =============================================================

Tpool = table( ...
    PoolIndex, ...
    Label, ...
    Architecture, ...
    NORAD, ...
    ObjectName, ...
    PositionECEF(:,1), ...
    PositionECEF(:,2), ...
    PositionECEF(:,3), ...
    Mask_deg, ...
    Azimuth_deg, ...
    Elevation_deg, ...
    SlantRange_m/1000, ...
    Visible, ...
    'VariableNames',{ ...
        'PoolIndex', ...
        'Label', ...
        'Architecture', ...
        'NORAD_CAT_ID', ...
        'ObjectName', ...
        'X_ECEF_m', ...
        'Y_ECEF_m', ...
        'Z_ECEF_m', ...
        'Mask_deg', ...
        'Azimuth_deg', ...
        'Elevation_deg', ...
        'SlantRange_km', ...
        'Visible'});

%% ============================================================
% Summary
% =============================================================

fprintf('\nPool composition:\n');
fprintf('HAPS : %d\n',sum(Architecture=="HAPS"));
fprintf('LEO  : %d\n',sum(Architecture=="LEO"));
fprintf('MEO  : %d\n',sum(Architecture=="MEO"));
fprintf('GEO  : %d\n',sum(Architecture=="GEO"));

fprintf('\nHAPS geometry:\n');

for k = idxHAPS
    fprintf( ...
        '%s: az = %.6f deg, el = %.6f deg, range = %.3f km\n', ...
        Label(k), ...
        Azimuth_deg(k), ...
        Elevation_deg(k), ...
        SlantRange_m(k)/1000);
end

fprintf('\n============================================================\n');
fprintf('NOMINAL 26-TX CANDIDATE POOL\n');
fprintf('============================================================\n');

disp(Tpool(:,{ ...
    'PoolIndex', ...
    'Label', ...
    'Architecture', ...
    'NORAD_CAT_ID', ...
    'ObjectName', ...
    'Azimuth_deg', ...
    'Elevation_deg', ...
    'SlantRange_km', ...
    'Visible'}));

%% ============================================================
% Save
% =============================================================

resultsDir = fullfile(rootDir,'results');

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

matFile = fullfile(resultsDir,'candidate_pool_26.mat');
csvFile = fullfile(resultsDir,'candidate_pool_26.csv');

save(matFile, ...
    'Tpool', ...
    'PoolIndex', ...
    'Label', ...
    'Architecture', ...
    'NORAD', ...
    'ObjectName', ...
    'PositionECEF', ...
    'Azimuth_deg', ...
    'Elevation_deg', ...
    'SlantRange_m', ...
    'Mask_deg', ...
    'Visible', ...
    'uLOS', ...
    'analysisTimeUTC', ...
    'UserPositionECEF', ...
    'userLat_deg', ...
    'userLon_deg', ...
    'userH_m', ...
    'nominalLEO', ...
    'nominalMEO', ...
    'nominalGEO', ...
    'hapsPositionECEF_m', ...
    'hapsDesignAzimuth_deg', ...
    'hapsDesignElevation_deg', ...
    'hapsAltitude_m');

writetable(Tpool,csvFile);

fprintf('\nMAT file:\n%s\n',matFile);
fprintf('\nCSV file:\n%s\n',csvFile);

fprintf('\n============================================================\n');
fprintf('26-TX CANDIDATE POOL COMPLETED\n');
fprintf('============================================================\n');


%% ============================================================
% Local function: append one orbital architecture
% =============================================================

function [nextIndex,Label,Architecture,NORAD,ObjectName,Mask_deg,PositionECEF] = ...
    appendArchitecture( ...
        Tcatalog, ...
        nextIndex, ...
        architectureName, ...
        nominalNORAD, ...
        mask_deg, ...
        Label, ...
        Architecture, ...
        NORAD, ...
        ObjectName, ...
        Mask_deg, ...
        PositionECEF)

    architectureName = string(architectureName);
    nominalNORAD = string(nominalNORAD(:));

    for j = 1:numel(nominalNORAD)

        norad = nominalNORAD(j);

        idx = ...
            Tcatalog.Architecture == architectureName & ...
            Tcatalog.NORAD_CAT_ID == norad;

        assert(sum(idx) == 1, ...
            'Could not uniquely match %s NORAD %s in orbital catalog.', ...
            architectureName,norad);

        k = nextIndex;

        Label(k)        = sprintf('%s%d',architectureName,j);
        Architecture(k) = architectureName;
        NORAD(k)        = norad;
        ObjectName(k)   = Tcatalog.ObjectName(idx);
        Mask_deg(k)     = mask_deg;

        PositionECEF(k,:) = [ ...
            Tcatalog.X_ECEF_m(idx), ...
            Tcatalog.Y_ECEF_m(idx), ...
            Tcatalog.Z_ECEF_m(idx)];

        nextIndex = nextIndex + 1;

    end

end


%% ============================================================
% Local function: ECEF -> azimuth/elevation/range/LOS
% =============================================================

function [az_deg,el_deg,range_m,uLOS] = ...
    lookAnglesECEF( ...
        rTx_m, ...
        rUser_m, ...
        userLat_deg, ...
        userLon_deg)

    rTx_m   = rTx_m(:);
    rUser_m = rUser_m(:);

    d = rTx_m-rUser_m;

    range_m = norm(d);

    if range_m <= 0
        error('Invalid transmitter/user geometry.');
    end

    uLOS = d/range_m;

    lat = userLat_deg*pi/180;
    lon = userLon_deg*pi/180;

    east = ...
        -sin(lon)*d(1) + ...
         cos(lon)*d(2);

    north = ...
        -sin(lat)*cos(lon)*d(1) ...
        -sin(lat)*sin(lon)*d(2) ...
        +cos(lat)*d(3);

    up = ...
         cos(lat)*cos(lon)*d(1) ...
        +cos(lat)*sin(lon)*d(2) ...
        +sin(lat)*d(3);

    az_deg = mod(atan2(east,north)*180/pi,360);

    el_deg = atan2(up,hypot(east,north))*180/pi;

end
