clear;
clc;

%% ============================================================
% BUILD LINK BUDGET
%
% Objective:
%   Compute the nominal measurement-quality parameters used by the
%   transmitter-selection experiments for the 26-transmitter candidate pool.
%
% The link-budget chain is
%
%   architecture parameters
%      -> free-space path loss
%      -> atmospheric gaseous attenuation
%      -> positioning-signal EIRP
%      -> C/N0
%      -> pseudorange standard deviation.
%
% Clear-sky gaseous attenuation is based on the ITU-R P.618/P.676 model.
% For the fixed experiment geometry, the corresponding validated values are
% read from:
%
%   data/atmospheric_gas_loss_reference.csv
%
% All remaining link-budget quantities are recomputed by this script.
%
% Ranging parameters:
%   beta   = 1.023 MHz
%   Tcoh   = 20 ms
%   etaPos = 0.01
%
% Outputs:
%   results/link_budget.mat
%   results/link_budget.csv
%% ============================================================

rootDir = fileparts(mfilename('fullpath'));

if isempty(rootDir)
    rootDir = pwd;
end

cd(rootDir);
setup_paths;

fprintf('\n============================================================\n');
fprintf('BUILD LINK BUDGET\n');
fprintf('============================================================\n');

%% ============================================================
% Input files
%% ============================================================

poolFile = fullfile( ...
    rootDir, ...
    'results', ...
    'candidate_pool_26.mat');

gasReferenceFile = fullfile( ...
    rootDir, ...
    'data', ...
    'atmospheric_gas_loss_reference.csv');

assert(isfile(poolFile), ...
    'Candidate pool not found:\n%s\nRun build_candidate_pool.m first.', ...
    poolFile);

assert(isfile(gasReferenceFile), ...
    'Atmospheric-loss reference not found:\n%s', ...
    gasReferenceFile);

%% ============================================================
% Candidate pool
%% ============================================================

P = load(poolFile);

assert(isfield(P,'Tpool') && istable(P.Tpool), ...
    'candidate_pool_26.mat must contain table Tpool.');

Tpool = P.Tpool;

requiredPoolVars = { ...
    'PoolIndex', ...
    'Label', ...
    'Architecture', ...
    'NORAD_CAT_ID', ...
    'ObjectName', ...
    'Elevation_deg', ...
    'SlantRange_km'};

for k = 1:numel(requiredPoolVars)

    assert(ismember( ...
        requiredPoolVars{k}, ...
        Tpool.Properties.VariableNames), ...
        'Missing candidate-pool variable: %s', ...
        requiredPoolVars{k});

end

Npool = height(Tpool);

assert(Npool == 26, ...
    'Expected 26 transmitters; found %d.',Npool);

PoolIndex   = Tpool.PoolIndex(:);
Label       = string(Tpool.Label(:));
Architecture = string(Tpool.Architecture(:));
NORAD       = string(Tpool.NORAD_CAT_ID(:));
ObjectName  = string(Tpool.ObjectName(:));

Elevation_deg = double(Tpool.Elevation_deg(:));
SlantRange_km = double(Tpool.SlantRange_km(:));
SlantRange_m  = 1000*SlantRange_km;

if isfield(P,'analysisTimeUTC')
    analysisTimeUTC = P.analysisTimeUTC;
else
    analysisTimeUTC = datetime( ...
        2026,8,1,12,0,0, ...
        'TimeZone','UTC');
end

if isfield(P,'userLat_deg')
    userLat_deg = P.userLat_deg;
else
    userLat_deg = -22.8596582;
end

if isfield(P,'userLon_deg')
    userLon_deg = P.userLon_deg;
else
    userLon_deg = -43.2303236;
end

if isfield(P,'userH_m')
    userH_m = P.userH_m;
else
    userH_m = 10.0;
end

%% ============================================================
% Atmospheric gaseous-loss reference
%% ============================================================

Tgas = readtable( ...
    gasReferenceFile, ...
    'TextType','string');

requiredGasVars = { ...
    'Architecture', ...
    'Label', ...
    'NORAD_CAT_ID', ...
    'AtmosphericGasLoss_dB'};

for k = 1:numel(requiredGasVars)

    assert(ismember( ...
        requiredGasVars{k}, ...
        Tgas.Properties.VariableNames), ...
        'Missing atmospheric-reference variable: %s', ...
        requiredGasVars{k});

end

Tgas.Architecture = string(Tgas.Architecture);
Tgas.Label = string(Tgas.Label);
Tgas.NORAD_CAT_ID = string(Tgas.NORAD_CAT_ID);

AtmosphericGasLoss_dB = nan(Npool,1);

for i = 1:Npool

    if Architecture(i) == "HAPS"

        idxGas = ...
            Tgas.Architecture == "HAPS" & ...
            Tgas.Label == Label(i);

    else

        idxGas = ...
            Tgas.Architecture == Architecture(i) & ...
            Tgas.NORAD_CAT_ID == NORAD(i);

    end

    if sum(idxGas) ~= 1

        error([ ...
            'Atmospheric-loss reference not uniquely found for ' ...
            '%s | %s | NORAD=%s.'], ...
            Label(i),Architecture(i),NORAD(i));

    end

    AtmosphericGasLoss_dB(i) = ...
        double(Tgas.AtmosphericGasLoss_dB(idxGas));

end

assert(all(isfinite(AtmosphericGasLoss_dB)));
assert(all(AtmosphericGasLoss_dB >= 0));

%% ============================================================
% Ranging parameters
%% ============================================================

c_mps  = 299792458;
beta   = 1.023e6;
Tcoh   = 20e-3;
etaPos = 0.01;

Branging_Hz  = beta;
Branging_MHz = beta/1e6;

GasAnnualExceedance_pct = 50.0;

PropagationModel = ...
    "free-space + fixed ITU-R P.618/P.676 clear-sky gaseous attenuation reference";

%% ============================================================
% RF architecture parameters
%% ============================================================

% HAPS
HAPS_Frequency_GHz    = 31.15;
HAPS_EIRP_PSD_dBW_MHz = -9.1;
HAPS_ReceiverFoM_dBK  = 12.3;

% LEO
LEO_Frequency_GHz = 20.0;
LEO_ReceiverFoM_dBK = 10.5;

LEO_ElevationControl_deg = [ ...
    10;
    25;
    90];

LEO_EIRP_Control_dBW_MHz = [ ...
    -2.7;
    17.9;
    11.3];

% MEO
MEO_Frequency_GHz = 20.0;
EIRP_MEO_total_dBW = 49.7;
BW_MEO_MHz = 100;
MEO_ReceiverFoM_dBK = 18.4;

% GEO
GEO_Frequency_GHz = 19.95;
EIRP_GEO_total_dBW = 57.0;
BW_GEO_MHz = 81.0;
G_rx_GEO_dBi = 44.5;
Tsys_GEO_K = 250;

%% ============================================================
% Architecture-dependent quantities
%% ============================================================

Frequency_GHz = nan(Npool,1);
EIRP_PSD_dBW_MHz = nan(Npool,1);
ReceiverFoM_dBK = nan(Npool,1);

ParameterSource = strings(Npool,1);
ReceiverChain = strings(Npool,1);

%% HAPS

idx = Architecture == "HAPS";

Frequency_GHz(idx) = ...
    HAPS_Frequency_GHz;

EIRP_PSD_dBW_MHz(idx) = ...
    HAPS_EIRP_PSD_dBW_MHz;

ReceiverFoM_dBK(idx) = ...
    HAPS_ReceiverFoM_dBK;

ParameterSource(idx) = ...
    "ITU-R F.2439 System 6: HAPS->CPE nominal parameters";

ReceiverChain(idx) = ...
    "HAPS reference CPE";

%% LEO

idx = Architecture == "LEO";

Frequency_GHz(idx) = ...
    LEO_Frequency_GHz;

ReceiverFoM_dBK(idx) = ...
    LEO_ReceiverFoM_dBK;

EIRP_PSD_dBW_MHz(idx) = ...
    starlinkEIRPFromElevation( ...
        Elevation_deg(idx), ...
        LEO_ElevationControl_deg, ...
        LEO_EIRP_Control_dBW_MHz);

ParameterSource(idx) = ...
    "SpaceX Gen2 Technical Attachment Table A.4-5 + interpolation";

ReceiverChain(idx) = ...
    "Starlink Gen2 user terminal";

%% MEO

idx = Architecture == "MEO";

Frequency_GHz(idx) = ...
    MEO_Frequency_GHz;

EIRP_PSD_MEO_dBW_MHz = ...
    EIRP_MEO_total_dBW ...
    - 10*log10(BW_MEO_MHz);

EIRP_PSD_dBW_MHz(idx) = ...
    EIRP_PSD_MEO_dBW_MHz;

ReceiverFoM_dBK(idx) = ...
    MEO_ReceiverFoM_dBK;

ParameterSource(idx) = ...
    "O3b mPOWER + mP85L reference";

ReceiverChain(idx) = ...
    "O3b mPOWER mP85L terminal";

%% GEO

idx = Architecture == "GEO";

Frequency_GHz(idx) = ...
    GEO_Frequency_GHz;

EIRP_PSD_GEO_dBW_MHz = ...
    EIRP_GEO_total_dBW ...
    - 10*log10(BW_GEO_MHz);

EIRP_PSD_dBW_MHz(idx) = ...
    EIRP_PSD_GEO_dBW_MHz;

ReceiverFoM_GEO_dBK = ...
    G_rx_GEO_dBi ...
    - 10*log10(Tsys_GEO_K);

ReceiverFoM_dBK(idx) = ...
    ReceiverFoM_GEO_dBK;

ParameterSource(idx) = ...
    "ITU-R S.1328-5 representative GSO Ka system";

ReceiverChain(idx) = ...
    "Representative GSO Ka earth station";

assert(all(isfinite(Frequency_GHz)));
assert(all(isfinite(EIRP_PSD_dBW_MHz)));
assert(all(isfinite(ReceiverFoM_dBK)));

%% ============================================================
% Free-space path loss
%% ============================================================

FSPL_dB = ...
    92.45 ...
    + 20*log10(SlantRange_km) ...
    + 20*log10(Frequency_GHz);

%% ============================================================
% Positioning-signal EIRP
%% ============================================================

EIRP_positioning_dBW = ...
    EIRP_PSD_dBW_MHz ...
    + 10*log10(Branging_MHz) ...
    + 10*log10(etaPos);

%% ============================================================
% Carrier-to-noise-density ratio
%% ============================================================

CN0_dBHz = ...
    EIRP_positioning_dBW ...
    - FSPL_dB ...
    - AtmosphericGasLoss_dB ...
    + ReceiverFoM_dBK ...
    + 228.6;

CN0_linear = ...
    10.^(CN0_dBHz/10);

%% ============================================================
% Pseudorange uncertainty
%% ============================================================

SigmaRho_m = ...
    c_mps ./ ...
    (2*pi*beta .* ...
    sqrt(CN0_linear*Tcoh));

VarianceRho_m2 = ...
    SigmaRho_m.^2;

%% Compatibility fields

AdditionalLoss_dB = zeros(Npool,1);
GT_dBK = ReceiverFoM_dBK;

%% ============================================================
% Output table
%% ============================================================

Tlink = table( ...
    PoolIndex, ...
    Label, ...
    Architecture, ...
    NORAD, ...
    ObjectName, ...
    Elevation_deg, ...
    SlantRange_km, ...
    Frequency_GHz, ...
    EIRP_PSD_dBW_MHz, ...
    ReceiverFoM_dBK, ...
    AtmosphericGasLoss_dB, ...
    AdditionalLoss_dB, ...
    FSPL_dB, ...
    EIRP_positioning_dBW, ...
    CN0_dBHz, ...
    SigmaRho_m, ...
    VarianceRho_m2, ...
    ReceiverChain, ...
    ParameterSource, ...
    'VariableNames',{ ...
    'PoolIndex', ...
    'Label', ...
    'Architecture', ...
    'NORAD_CAT_ID', ...
    'ObjectName', ...
    'Elevation_deg', ...
    'SlantRange_km', ...
    'Frequency_GHz', ...
    'EIRP_PSD_dBW_MHz', ...
    'ReceiverFoM_dBK', ...
    'AtmosphericGasLoss_dB', ...
    'AdditionalLoss_dB', ...
    'FSPL_dB', ...
    'EIRP_positioning_dBW', ...
    'CN0_dBHz', ...
    'SigmaRho_m', ...
    'VarianceRho_m2', ...
    'ReceiverChain', ...
    'ParameterSource'});

%% ============================================================
% Summary
%% ============================================================

fprintf('\n============================================================\n');
fprintf('LINK-BUDGET SUMMARY\n');
fprintf('============================================================\n');

architectures = ["HAPS","LEO","MEO","GEO"];

for a = 1:numel(architectures)

    arch = architectures(a);
    idx = Architecture == arch;

    fprintf('\n%s\n',arch);

    fprintf('C/N0 min / max       = %.3f / %.3f dB-Hz\n', ...
        min(CN0_dBHz(idx)), ...
        max(CN0_dBHz(idx)));

    fprintf('SigmaRho min / max   = %.6f / %.6f m\n', ...
        min(SigmaRho_m(idx)), ...
        max(SigmaRho_m(idx)));

    fprintf('Gas loss min / max   = %.6f / %.6f dB\n', ...
        min(AtmosphericGasLoss_dB(idx)), ...
        max(AtmosphericGasLoss_dB(idx)));

end

%% ============================================================
% Save
%% ============================================================

resultsDir = fullfile(rootDir,'results');

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

matFile = fullfile( ...
    resultsDir, ...
    'link_budget.mat');

csvFile = fullfile( ...
    resultsDir, ...
    'link_budget.csv');

save(matFile, ...
    'Tlink', ...
    'Label', ...
    'Architecture', ...
    'NORAD', ...
    'ObjectName', ...
    'Elevation_deg', ...
    'SlantRange_m', ...
    'Frequency_GHz', ...
    'EIRP_PSD_dBW_MHz', ...
    'ReceiverFoM_dBK', ...
    'GT_dBK', ...
    'AtmosphericGasLoss_dB', ...
    'AdditionalLoss_dB', ...
    'FSPL_dB', ...
    'EIRP_positioning_dBW', ...
    'CN0_dBHz', ...
    'CN0_linear', ...
    'SigmaRho_m', ...
    'VarianceRho_m2', ...
    'ReceiverChain', ...
    'ParameterSource', ...
    'analysisTimeUTC', ...
    'userLat_deg', ...
    'userLon_deg', ...
    'userH_m', ...
    'beta', ...
    'Tcoh', ...
    'etaPos', ...
    'Branging_Hz', ...
    'Branging_MHz', ...
    'GasAnnualExceedance_pct', ...
    'PropagationModel');

writetable(Tlink,csvFile);

fprintf('\nMAT file:\n%s\n',matFile);
fprintf('\nCSV file:\n%s\n',csvFile);

fprintf('\n============================================================\n');
fprintf('LINK BUDGET COMPLETED\n');
fprintf('============================================================\n');


%% ============================================================
% Local function: LEO EIRP interpolation
%% ============================================================

function eirp = starlinkEIRPFromElevation( ...
    elevation_deg, ...
    controlElevation_deg, ...
    controlEIRP_dBW_MHz)

    elevation_deg = elevation_deg(:);

    elevClamped = min( ...
        max(elevation_deg,min(controlElevation_deg)), ...
        max(controlElevation_deg));

    eirp = interp1( ...
        controlElevation_deg, ...
        controlEIRP_dBW_MHz, ...
        elevClamped, ...
        'linear');

    eirp = eirp(:);

end
