clear;
clc;
format long;

%% ============================================================
% BUILD NOMINAL 26-TRANSMITTER CANDIDATE POOL
%
% Canonical location:
%   matlab/setup/build_nominal_candidate_pool.m
%
% Inputs:
%   results/orbital_catalog.mat
%
% Outputs:
%   results/candidate_pool_26.mat
%   results/candidate_pool_26.csv
%
% Composition:
%   4 synthetic HAPS
%   8 LEO
%   7 MEO
%   7 GEO
%
% Geometry:
%   - HAPS: synthetic fixed locations at 20 km altitude
%   - Orbital candidates: corrected Vallado SGP4/WGS-72 states
%
% No dependency on the old thesis repository.
% ============================================================

%% Repository root

thisFile = mfilename('fullpath');

if isempty(thisFile)
    error('This script must be executed from a saved .m file.');
end

repoRoot = fileparts(thisFile);

while ~isfolder(fullfile(repoRoot,'.git'))

    parentDir = fileparts(repoRoot);

    if strcmp(parentDir,repoRoot)
        error('Could not locate Git repository root from:\n%s',thisFile);
    end

    repoRoot = parentDir;
end

setupFile = fullfile(repoRoot,'matlab','setup','setup_paths.m');

assert(isfile(setupFile), ...
    'setup_paths.m not found:\n%s',setupFile);

addpath(fullfile(repoRoot,'matlab','setup'),'-begin');
setup_paths;

fprintf('\n============================================================\n');
fprintf('BUILD NOMINAL CANDIDATE POOL\n');
fprintf('============================================================\n');
fprintf('Repository:\n%s\n',repoRoot);

%% Input orbital catalog

catalogFile = fullfile( ...
    repoRoot,'results','orbital_catalog.mat');

assert(isfile(catalogFile), ...
    ['Orbital catalog not found:\n%s\n' ...
     'Run build_orbital_catalog.m first.'], ...
    catalogFile);

C = load(catalogFile);

requiredCatalogVars = [ ...
    "TOrbitalCatalog", ...
    "analysisTimeUTC", ...
    "UserPositionECEF", ...
    "userLat_deg", ...
    "userLon_deg", ...
    "userH_m"];

for k = 1:numel(requiredCatalogVars)
    assert(isfield(C,requiredCatalogVars(k)), ...
        'Missing orbital-catalog variable: %s', ...
        requiredCatalogVars(k));
end

Tcatalog = C.TOrbitalCatalog;

analysisTimeUTC = C.analysisTimeUTC;
UserPositionECEF = double(C.UserPositionECEF(:).');
userLat_deg = double(C.userLat_deg);
userLon_deg = double(C.userLon_deg);
userH_m = double(C.userH_m);

Tcatalog.Architecture = upper(string(Tcatalog.Architecture));
Tcatalog.NORAD_CAT_ID = string(Tcatalog.NORAD_CAT_ID);
Tcatalog.ObjectName = string(Tcatalog.ObjectName);

%% Exact nominal orbital identities and ordering

LEO_NORAD = [ ...
    "65175"
    "66864"
    "65348"
    "59340"
    "67736"
    "59960"
    "65279"
    "48482"];

MEO_NORAD = [ ...
    "62362"
    "40081"
    "44115"
    "43231"
    "43234"
    "40080"
    "40079"];

GEO_NORAD = [ ...
    "41589"
    "41904"
    "42692"
    "43562"
    "43175"
    "43228"
    "38087"];

TLEO = selectCatalogByNORAD(Tcatalog,"LEO",LEO_NORAD);
TMEO = selectCatalogByNORAD(Tcatalog,"MEO",MEO_NORAD);
TGEO = selectCatalogByNORAD(Tcatalog,"GEO",GEO_NORAD);

%% Synthetic HAPS design

hapsAltitude_m = 20e3;

hapsAzimuthTarget_deg = [ ...
     45
    135
    225
    315];

hapsElevationTarget_deg = [ ...
    80
    30
    30
    25];

nHAPS = numel(hapsAzimuthTarget_deg);

hapsPositionECEF_m = zeros(nHAPS,3);
hapsAzimuth_deg = zeros(nHAPS,1);
hapsElevation_deg = zeros(nHAPS,1);
hapsSlantRange_m = zeros(nHAPS,1);

for k = 1:nHAPS

    [~,~,~,hapsPositionECEF_m(k,:)] = ...
        solveHAPSOffsetForElevation( ...
            userLat_deg, ...
            userLon_deg, ...
            UserPositionECEF, ...
            hapsAltitude_m, ...
            hapsAzimuthTarget_deg(k), ...
            hapsElevationTarget_deg(k));

    [hapsAzimuth_deg(k), ...
     hapsElevation_deg(k), ...
     hapsSlantRange_m(k),~] = ...
        ecefAzElRange( ...
            UserPositionECEF, ...
            hapsPositionECEF_m(k,:), ...
            userLat_deg, ...
            userLon_deg);
end

%% Assemble pool

Npool = 26;

PoolIndex = (1:Npool).';

Label = strings(Npool,1);
Architecture = strings(Npool,1);
NORAD = strings(Npool,1);
ObjectName = strings(Npool,1);

PositionECEF = zeros(Npool,3);
Azimuth_deg = zeros(Npool,1);
Elevation_deg = zeros(Npool,1);
SlantRange_m = zeros(Npool,1);
Mask_deg = zeros(Npool,1);
Visible = false(Npool,1);
uLOS = zeros(Npool,3);

row = 0;

%% HAPS rows

for k = 1:nHAPS

    row = row+1;

    Label(row) = "HAPS" + string(k);
    Architecture(row) = "HAPS";
    NORAD(row) = "";
    ObjectName(row) = Label(row);

    PositionECEF(row,:) = hapsPositionECEF_m(k,:);
    Azimuth_deg(row) = hapsAzimuth_deg(k);
    Elevation_deg(row) = hapsElevation_deg(k);
    SlantRange_m(row) = hapsSlantRange_m(k);
    Mask_deg(row) = 15;

    delta = PositionECEF(row,:) - UserPositionECEF;
    uLOS(row,:) = delta/norm(delta);

    Visible(row) = Elevation_deg(row)>=Mask_deg(row);
end

%% Orbital rows

orbitalGroups = {TLEO,TMEO,TGEO};
orbitalLabels = ["LEO","MEO","GEO"];

for g = 1:numel(orbitalGroups)

    T = orbitalGroups{g};
    arch = orbitalLabels(g);

    for k = 1:height(T)

        row = row+1;

        Label(row) = arch + string(k);
        Architecture(row) = arch;
        NORAD(row) = string(T.NORAD_CAT_ID(k));
        ObjectName(row) = string(T.ObjectName(k));

        PositionECEF(row,:) = [ ...
            double(T.X_ECEF_m(k)), ...
            double(T.Y_ECEF_m(k)), ...
            double(T.Z_ECEF_m(k))];

        Azimuth_deg(row) = double(T.Azimuth_deg(k));
        Elevation_deg(row) = double(T.Elevation_deg(k));
        SlantRange_m(row) = 1000*double(T.SlantRange_km(k));
        Mask_deg(row) = 5;

        delta = PositionECEF(row,:) - UserPositionECEF;
        uLOS(row,:) = delta/norm(delta);

        Visible(row) = Elevation_deg(row)>=Mask_deg(row);
    end
end

assert(row==Npool, ...
    'Candidate-pool assembly error: expected %d rows, built %d.', ...
    Npool,row);

%% Sanity checks

assert(sum(Architecture=="HAPS")==4);
assert(sum(Architecture=="LEO")==8);
assert(sum(Architecture=="MEO")==7);
assert(sum(Architecture=="GEO")==7);

assert(all(Visible), ...
    'At least one nominal candidate is below its elevation mask.');

assert(all(isfinite(PositionECEF),'all'));
assert(all(isfinite(Elevation_deg)));
assert(all(isfinite(SlantRange_m)));
assert(all(SlantRange_m>0));

%% Candidate-pool table

Tpool = table( ...
    PoolIndex, ...
    Label, ...
    Architecture, ...
    NORAD, ...
    ObjectName, ...
    PositionECEF(:,1), ...
    PositionECEF(:,2), ...
    PositionECEF(:,3), ...
    Azimuth_deg, ...
    Elevation_deg, ...
    SlantRange_m/1000, ...
    Mask_deg, ...
    Visible, ...
    'VariableNames',{ ...
    'PoolIndex', ...
    'Label', ...
    'Architecture', ...
    'NORAD_CAT_ID', ...
    'ObjectName', ...
    'X_ECEF_m', ...
    'Y_ECEF_m', ...
    'Z_ECEF_m', ...
    'Azimuth_deg', ...
    'Elevation_deg', ...
    'SlantRange_km', ...
    'Mask_deg', ...
    'Visible'});

%% Report

fprintf('\nPool composition\n');
fprintf('HAPS : %d\n',sum(Architecture=="HAPS"));
fprintf('LEO  : %d\n',sum(Architecture=="LEO"));
fprintf('MEO  : %d\n',sum(Architecture=="MEO"));
fprintf('GEO  : %d\n',sum(Architecture=="GEO"));
fprintf('Total: %d\n',Npool);

fprintf('\nHAPS geometry\n');

for k = 1:4
    fprintf('%s: az = %.6f deg | el = %.6f deg | range = %.6f km\n', ...
        Label(k), ...
        Azimuth_deg(k), ...
        Elevation_deg(k), ...
        SlantRange_m(k)/1000);
end

fprintf('\nNominal orbital identities\n');
fprintf('LEO: %s\n',strjoin(NORAD(Architecture=="LEO")," "));
fprintf('MEO: %s\n',strjoin(NORAD(Architecture=="MEO")," "));
fprintf('GEO: %s\n',strjoin(NORAD(Architecture=="GEO")," "));

%% Save

resultsDir = fullfile(repoRoot,'results');

if ~isfolder(resultsDir)
    mkdir(resultsDir);
end

matFile = fullfile( ...
    resultsDir,'candidate_pool_26.mat');

csvFile = fullfile( ...
    resultsDir,'candidate_pool_26.csv');

save( ...
    matFile, ...
    'Tpool', ...
    'PoolIndex', ...
    'Label', ...
    'Architecture', ...
    'NORAD', ...
    'ObjectName', ...
    'PositionECEF', ...
    'Azimuth_deg', ...
    'Elevation_deg', ...
    'SlantRange_m', ...
    'Mask_deg', ...
    'Visible', ...
    'uLOS', ...
    'analysisTimeUTC', ...
    'UserPositionECEF', ...
    'userLat_deg', ...
    'userLon_deg', ...
    'userH_m', ...
    'LEO_NORAD', ...
    'MEO_NORAD', ...
    'GEO_NORAD', ...
    'hapsAltitude_m', ...
    'hapsAzimuthTarget_deg', ...
    'hapsElevationTarget_deg');

writetable(Tpool,csvFile);

fprintf('\nSaved:\n');
fprintf('%s\n',matFile);
fprintf('%s\n',csvFile);

fprintf('\n============================================================\n');
fprintf('NOMINAL CANDIDATE POOL COMPLETED\n');
fprintf('============================================================\n');

%% ============================================================
% Local functions
% =============================================================

function Tsel = ...
    selectCatalogByNORAD(Tcatalog,architecture,noradList)

    Tsel = Tcatalog([],:);

    for k = 1:numel(noradList)

        idx = ...
            Tcatalog.Architecture==architecture & ...
            Tcatalog.NORAD_CAT_ID==noradList(k);

        assert(sum(idx)==1, ...
            'Could not uniquely find %s NORAD %s in orbital catalog.', ...
            architecture,noradList(k));

        Tsel = [Tsel; Tcatalog(idx,:)]; %#ok<AGROW>
    end
end

function [offset_m,hapsLat_deg,hapsLon_deg,posECEF] = ...
    solveHAPSOffsetForElevation( ...
        userLat_deg, ...
        userLon_deg, ...
        UserPositionECEF, ...
        hapsAltitude_m, ...
        azimuth_deg, ...
        targetElevation_deg)

    low_m = 0;
    high_m = 100e3;

    [~,elLow] = ...
        hapsPositionAtOffset( ...
            low_m, ...
            userLat_deg, ...
            userLon_deg, ...
            UserPositionECEF, ...
            hapsAltitude_m, ...
            azimuth_deg);

    [~,elHigh] = ...
        hapsPositionAtOffset( ...
            high_m, ...
            userLat_deg, ...
            userLon_deg, ...
            UserPositionECEF, ...
            hapsAltitude_m, ...
            azimuth_deg);

    while elHigh>targetElevation_deg && high_m<500e3

        high_m = 1.5*high_m;

        [~,elHigh] = ...
            hapsPositionAtOffset( ...
                high_m, ...
                userLat_deg, ...
                userLon_deg, ...
                UserPositionECEF, ...
                hapsAltitude_m, ...
                azimuth_deg);
    end

    assert( ...
        elLow>=targetElevation_deg && ...
        elHigh<=targetElevation_deg, ...
        'Could not bracket target HAPS elevation %.3f deg.', ...
        targetElevation_deg);

    for iter = 1:80

        mid_m = 0.5*(low_m+high_m);

        [~,elMid] = ...
            hapsPositionAtOffset( ...
                mid_m, ...
                userLat_deg, ...
                userLon_deg, ...
                UserPositionECEF, ...
                hapsAltitude_m, ...
                azimuth_deg);

        if elMid>targetElevation_deg
            low_m = mid_m;
        else
            high_m = mid_m;
        end
    end

    offset_m = 0.5*(low_m+high_m);

    [posECEF,~,hapsLat_deg,hapsLon_deg] = ...
        hapsPositionAtOffset( ...
            offset_m, ...
            userLat_deg, ...
            userLon_deg, ...
            UserPositionECEF, ...
            hapsAltitude_m, ...
            azimuth_deg);
end

function [posECEF,elevation_deg,latH_deg,lonH_deg] = ...
    hapsPositionAtOffset( ...
        offset_m, ...
        userLat_deg, ...
        userLon_deg, ...
        UserPositionECEF, ...
        hapsAltitude_m, ...
        azimuth_deg)

    a = 6378137.0;
    f = 1/298.257223563;
    e2 = f*(2-f);

    lat0 = deg2rad(userLat_deg);
    lon0 = deg2rad(userLon_deg);

    N0 = a/sqrt(1-e2*sin(lat0)^2);
    M0 = a*(1-e2)/(1-e2*sin(lat0)^2)^(3/2);

    east_m = offset_m*sind(azimuth_deg);
    north_m = offset_m*cosd(azimuth_deg);

    latH_deg = rad2deg(lat0+north_m/M0);
    lonH_deg = rad2deg(lon0+east_m/(N0*cos(lat0)));

    posECEF = ...
        geodeticToECEFWGS84( ...
            latH_deg,lonH_deg,hapsAltitude_m);

    [~,elevation_deg,~,~] = ...
        ecefAzElRange( ...
            UserPositionECEF, ...
            posECEF, ...
            userLat_deg, ...
            userLon_deg);
end

function rECEF_m = ...
    geodeticToECEFWGS84(lat_deg,lon_deg,h_m)

    a = 6378137.0;
    f = 1/298.257223563;
    e2 = f*(2-f);

    lat = deg2rad(lat_deg);
    lon = deg2rad(lon_deg);

    N = a/sqrt(1-e2*sin(lat)^2);

    x = (N+h_m)*cos(lat)*cos(lon);
    y = (N+h_m)*cos(lat)*sin(lon);
    z = (N*(1-e2)+h_m)*sin(lat);

    rECEF_m = [x,y,z];
end

function [az_deg,el_deg,range_m,uLOS] = ...
    ecefAzElRange( ...
        rUser_m, ...
        rTx_m, ...
        userLat_deg, ...
        userLon_deg)

    rUser_m = rUser_m(:).';
    rTx_m = rTx_m(:).';

    d = rTx_m-rUser_m;

    range_m = norm(d);

    assert(range_m>0, ...
        'Invalid transmitter/user geometry.');

    uLOS = d/range_m;

    lat = deg2rad(userLat_deg);
    lon = deg2rad(userLon_deg);

    east = ...
        -sin(lon)*d(1) + ...
         cos(lon)*d(2);

    north = ...
        -sin(lat)*cos(lon)*d(1) ...
        -sin(lat)*sin(lon)*d(2) ...
        +cos(lat)*d(3);

    up = ...
         cos(lat)*cos(lon)*d(1) ...
        +cos(lat)*sin(lon)*d(2) ...
        +sin(lat)*d(3);

    az_deg = mod(atan2d(east,north),360);
    el_deg = atan2d(up,hypot(east,north));
end