clear;
clc;

%% ============================================================
%  COMPARE OLD PAPER CATALOG vs CORRECTED VALLADO CATALOG
%
%  Purpose:
%    Compare the orbital states originally used in the paper
%    (MATLAB satelliteScenario SGP4) against the corrected
%    Vallado SGP4 orbital catalog.
%
%  Epoch:
%    01-Aug-2026 12:00:00 UTC
%
%  Architectures:
%    20 LEO
%     7 MEO
%     7 GEO
% =============================================================

%% Repository root

rootDir = fileparts(fileparts(mfilename('fullpath')));

cd(rootDir);
setup_paths;

fprintf('\n============================================================\n');
fprintf('OLD PAPER CATALOG vs CORRECTED VALLADO CATALOG\n');
fprintf('============================================================\n');

%% ============================================================
%  Old orbital catalog actually used in the paper
% =============================================================

oldRoot = ...
    'C:\Repository\master-thesis-ntn-positioning';

oldFile = fullfile( ...
    oldRoot, ...
    'matlab_code', ...
    'results_scenario4_preparation', ...
    'scenario4_orbital_catalog.mat');

assert(isfile(oldFile), ...
    'Old orbital catalog not found:\n%s',oldFile);

O = load(oldFile);

assert(isfield(O,'TLEO20'), ...
    'TLEO20 not found in old catalog.');

assert(isfield(O,'TMEO7'), ...
    'TMEO7 not found in old catalog.');

assert(isfield(O,'TGEO7'), ...
    'TGEO7 not found in old catalog.');

%% ============================================================
%  Corrected Vallado catalog
% =============================================================

newFile = fullfile( ...
    rootDir, ...
    'results', ...
    'orbital_catalog.mat');

assert(isfile(newFile), ...
    'Corrected Vallado catalog not found:\n%s',newFile);

N = load(newFile);

assert(isfield(N,'TOrbitalCatalog'), ...
    'TOrbitalCatalog not found in Vallado catalog.');

%% ============================================================
%  Analysis epochs
% =============================================================

fprintf('\nOld catalog epoch      : %s\n', ...
    string(O.analysisTimeUTC));

fprintf('Corrected catalog epoch: %s\n', ...
    string(N.analysisTimeUTC));

assert( ...
    abs(seconds(O.analysisTimeUTC - N.analysisTimeUTC)) < 1e-6, ...
    'Old and corrected catalogs use different epochs.');

%% ============================================================
%  Build common OLD table
% =============================================================

oldTables = { ...
    O.TLEO20, ...
    O.TMEO7, ...
    O.TGEO7};

TOld = [];

for a = 1:numel(oldTables)

    T = oldTables{a};

    Tpart = table( ...
        string(T.Architecture), ...
        string(T.NORAD_CAT_ID), ...
        string(T.ObjectName), ...
        T.X_ECEF_m, ...
        T.Y_ECEF_m, ...
        T.Z_ECEF_m, ...
        T.Azimuth_deg, ...
        T.Elevation_deg, ...
        T.SlantRange_km, ...
        logical(T.Visible), ...
        'VariableNames',{ ...
        'Architecture', ...
        'NORAD_CAT_ID', ...
        'ObjectName', ...
        'X_old_m', ...
        'Y_old_m', ...
        'Z_old_m', ...
        'Az_old_deg', ...
        'El_old_deg', ...
        'Range_old_km', ...
        'Visible_old'});

    if isempty(TOld)
        TOld = Tpart;
    else
        TOld = [TOld; Tpart]; %#ok<AGROW>
    end

end

assert(height(TOld) == 34, ...
    'Expected 34 objects in old catalog, found %d.', ...
    height(TOld));

%% ============================================================
%  Build common NEW table
% =============================================================

T = N.TOrbitalCatalog;

TNew = table( ...
    string(T.Architecture), ...
    string(T.NORAD_CAT_ID), ...
    string(T.ObjectName), ...
    T.X_ECEF_m, ...
    T.Y_ECEF_m, ...
    T.Z_ECEF_m, ...
    T.Azimuth_deg, ...
    T.Elevation_deg, ...
    T.SlantRange_km, ...
    logical(T.Visible), ...
    'VariableNames',{ ...
    'Architecture', ...
    'NORAD_CAT_ID', ...
    'ObjectName_new', ...
    'X_new_m', ...
    'Y_new_m', ...
    'Z_new_m', ...
    'Az_new_deg', ...
    'El_new_deg', ...
    'Range_new_km', ...
    'Visible_new'});

assert(height(TNew) == 34, ...
    'Expected 34 objects in corrected catalog, found %d.', ...
    height(TNew));

%% ============================================================
%  Join catalogs using Architecture + NORAD ID
% =============================================================

C = innerjoin( ...
    TOld, ...
    TNew, ...
    'Keys',{'Architecture','NORAD_CAT_ID'});

assert(height(C) == 34, ...
    ['Expected 34 matched objects after join, ' ...
     'but found %d.'], ...
    height(C));

%% ============================================================
%  Position differences
% =============================================================

C.dX_m = ...
    C.X_new_m - C.X_old_m;

C.dY_m = ...
    C.Y_new_m - C.Y_old_m;

C.dZ_m = ...
    C.Z_new_m - C.Z_old_m;

C.PositionDiff3D_m = sqrt( ...
    C.dX_m.^2 + ...
    C.dY_m.^2 + ...
    C.dZ_m.^2);

%% ============================================================
%  Geometry differences
% =============================================================

% Circular azimuth difference in [-180,180] deg
C.AzimuthDiff_deg = mod( ...
    C.Az_new_deg - C.Az_old_deg + 180, ...
    360) - 180;

C.ElevationDiff_deg = ...
    C.El_new_deg - C.El_old_deg;

C.RangeDiff_m = ...
    1000 .* ...
    (C.Range_new_km - C.Range_old_km);

C.VisibilityChanged = ...
    C.Visible_new ~= C.Visible_old;

%% ============================================================
%  Architecture summary
% =============================================================

fprintf('\n============================================================\n');
fprintf('COMPARISON SUMMARY\n');
fprintf('Epoch: 01-Aug-2026 12:00:00 UTC\n');
fprintf('============================================================\n');

architectures = ["LEO","MEO","GEO"];

for a = 1:numel(architectures)

    arch = architectures(a);

    idx = C.Architecture == arch;

    fprintf('\n%s (%d satellites)\n', ...
        arch,sum(idx));

    fprintf('\nPosition difference [m]\n');

    fprintf(' mean   = %.3f\n', ...
        mean(C.PositionDiff3D_m(idx)));

    fprintf(' median = %.3f\n', ...
        median(C.PositionDiff3D_m(idx)));

    fprintf(' max    = %.3f\n', ...
        max(C.PositionDiff3D_m(idx)));

    fprintf('\nGeometry differences\n');

    fprintf(' max |azimuth difference|   = %.6f deg\n', ...
        max(abs(C.AzimuthDiff_deg(idx))));

    fprintf(' max |elevation difference| = %.6f deg\n', ...
        max(abs(C.ElevationDiff_deg(idx))));

    fprintf(' max |range difference|     = %.3f m\n', ...
        max(abs(C.RangeDiff_m(idx))));

    fprintf(' visibility changes          = %d\n', ...
        sum(C.VisibilityChanged(idx)));

end

%% ============================================================
%  Global summary
% =============================================================

fprintf('\n============================================================\n');
fprintf('ALL ORBITAL SATELLITES (%d)\n',height(C));
fprintf('============================================================\n');

fprintf('\nPosition difference [m]\n');

fprintf(' mean   = %.3f\n', ...
    mean(C.PositionDiff3D_m));

fprintf(' median = %.3f\n', ...
    median(C.PositionDiff3D_m));

fprintf(' max    = %.3f\n', ...
    max(C.PositionDiff3D_m));

fprintf('\nGeometry differences\n');

fprintf(' maximum |azimuth difference|   = %.6f deg\n', ...
    max(abs(C.AzimuthDiff_deg)));

fprintf(' maximum |elevation difference| = %.6f deg\n', ...
    max(abs(C.ElevationDiff_deg)));

fprintf(' maximum |range difference|     = %.3f m\n', ...
    max(abs(C.RangeDiff_m)));

fprintf(' total visibility changes       = %d\n', ...
    sum(C.VisibilityChanged));

%% ============================================================
%  Largest position differences
% =============================================================

Csorted = sortrows( ...
    C, ...
    'PositionDiff3D_m', ...
    'descend');

fprintf('\n============================================================\n');
fprintf('LARGEST POSITION DIFFERENCES\n');
fprintf('============================================================\n');

nShow = min(10,height(Csorted));

for k = 1:nShow

    fprintf([ ...
        '%2d. %-3s  NORAD %-6s  %-22s  ' ...
        '%9.3f m   dEl=%+.6f deg   dRange=%+.3f m\n'], ...
        k, ...
        char(Csorted.Architecture(k)), ...
        char(Csorted.NORAD_CAT_ID(k)), ...
        char(Csorted.ObjectName(k)), ...
        Csorted.PositionDiff3D_m(k), ...
        Csorted.ElevationDiff_deg(k), ...
        Csorted.RangeDiff_m(k));

end

%% ============================================================
%  Objects closest to elevation mask
% =============================================================

fprintf('\n============================================================\n');
fprintf('LOWEST ELEVATION OBJECTS - CORRECTED CATALOG\n');
fprintf('============================================================\n');

[~,idxEl] = sort(C.El_new_deg,'ascend');

nShow = min(10,height(C));

for k = 1:nShow

    j = idxEl(k);

    fprintf([ ...
        '%2d. %-3s  NORAD %-6s  %-22s  ' ...
        'old=%8.4f deg  new=%8.4f deg  dEl=%+.6f deg\n'], ...
        k, ...
        char(C.Architecture(j)), ...
        char(C.NORAD_CAT_ID(j)), ...
        char(C.ObjectName(j)), ...
        C.El_old_deg(j), ...
        C.El_new_deg(j), ...
        C.ElevationDiff_deg(j));

end

%% ============================================================
%  Save detailed comparison
% =============================================================

resultsDir = fullfile(rootDir,'results');

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

csvFile = fullfile( ...
    resultsDir, ...
    'comparison_old_vs_vallado_catalog.csv');

matFile = fullfile( ...
    resultsDir, ...
    'comparison_old_vs_vallado_catalog.mat');

writetable(C,csvFile);

save(matFile, ...
    'C', ...
    'TOld', ...
    'TNew');

fprintf('\n============================================================\n');
fprintf('COMPARISON COMPLETED\n');
fprintf('============================================================\n');

fprintf('\nCSV saved to:\n%s\n',csvFile);

fprintf('\nMAT saved to:\n%s\n',matFile);