clear;
clc;

%% Paths

thisFile  = mfilename('fullpath');
atmDir    = fileparts(thisFile);
matlabDir = fileparts(atmDir);
repoRoot  = fileparts(matlabDir);

addpath(atmDir);

%% Candidate pool

S = load(fullfile( ...
    repoRoot,'data','generated', ...
    'nominal_candidate_pool.mat'));

candidatePool = S.candidatePool;

%% Previous MATLAB toolbox result

L = load(fullfile( ...
    repoRoot,'data','generated', ...
    'nominal_link_budget.mat'));

oldLoss_dB = ...
    L.linkBudget.AtmosphericGasLoss_dB;

%% P.2145 maps

p2145Dir = fullfile( ...
    repoRoot,'data','itu','p2145','annual');

met = itu2145_annual50_at_location( ...
    p2145Dir, ...
    -22.8596582, ...
    -43.2303236, ...
    10);

%% P.676-13 Annex 2

N = height(candidatePool);

newLoss_dB = nan(N,1);

for k = 1:N

    newLoss_dB(k) = ...
        itu676_annex2_slant_gas_loss( ...
            candidatePool.Frequency_GHz(k), ...
            candidatePool.Elevation_deg(k), ...
            0.010, ...
            met);
end

%% Comparison

delta_dB = newLoss_dB-oldLoss_dB;

relative_pct = ...
    100*delta_dB./oldLoss_dB;

comparison = table( ...
    candidatePool.Label, ...
    candidatePool.Architecture, ...
    candidatePool.Elevation_deg, ...
    candidatePool.Frequency_GHz, ...
    oldLoss_dB, ...
    newLoss_dB, ...
    delta_dB, ...
    relative_pct, ...
    'VariableNames',{ ...
    'Label', ...
    'Architecture', ...
    'Elevation_deg', ...
    'Frequency_GHz', ...
    'MATLAB_dB', ...
    'P2145_P676_dB', ...
    'Difference_dB', ...
    'Difference_pct'});

disp(comparison);

fprintf('\n');
fprintf('==============================================\n');
fprintf('P.2145 + P.676-13 COMPARISON\n');
fprintf('==============================================\n');

fprintf('Mean absolute difference    : %.6f dB\n', ...
    mean(abs(delta_dB)));

fprintf('Maximum absolute difference : %.6f dB\n', ...
    max(abs(delta_dB)));

fprintf('Mean relative difference    : %.3f %%\n', ...
    mean(abs(relative_pct)));

fprintf('==============================================\n');